let CANVAS_SIZE = 800;
let GRID_SIZE = 40;
let SCALE = CANVAS_SIZE / GRID_SIZE;
let FRAME_RATE = 60;
let TICK_RATE = 5;
let SPEED_MUL = 0.25
let DEBUG = false

export {CANVAS_SIZE, GRID_SIZE, SCALE, FRAME_RATE, TICK_RATE, SPEED_MUL, DEBUG}
